// ============================================================
// Sudaneel Logistics Intelligence Platform — Realistic Domain Data
// ============================================================

import {
  Shipment,
  Vehicle,
  Carrier,
  Driver,
  BackhaulOpportunity,
  Incident,
  Invoice,
  WalletTransaction,
} from '@/types';

export const mockCarriers: Carrier[] = [
  {
    id: 'car-01',
    name: 'Nile Express Heavy Haulage',
    nameAr: 'ناقلات النيل إكسبريس للشحن الثقيل',
    email: 'dispatch@nileexpress.sd',
    phone: '+249 912 300 110',
    city: 'Khartoum',
    fleetCount: 38,
    activeTrips: 14,
    trustScore: 96,
    onTimeDeliveryRate: 97.4,
    cancellationRate: 1.2,
    damageRate: 0.3,
    totalTrips: 1840,
    isVerified: true,
    ratingCategory: 'Platinum',
  },
  {
    id: 'car-02',
    name: 'Red Sea International Freight',
    nameAr: 'شحن البحر الأحمر الدولي',
    email: 'ops@redseafreight.sd',
    phone: '+249 912 300 220',
    city: 'Port Sudan',
    fleetCount: 45,
    activeTrips: 19,
    trustScore: 94,
    onTimeDeliveryRate: 95.8,
    cancellationRate: 1.8,
    damageRate: 0.5,
    totalTrips: 2420,
    isVerified: true,
    ratingCategory: 'Platinum',
  },
  {
    id: 'car-03',
    name: 'Blue Nile Transport Alliance',
    nameAr: 'تحالف النيل الأزرق للنقل',
    email: 'info@blueniletrans.sd',
    phone: '+249 912 300 330',
    city: 'Wad Madani',
    fleetCount: 22,
    activeTrips: 8,
    trustScore: 89,
    onTimeDeliveryRate: 91.2,
    cancellationRate: 2.5,
    damageRate: 0.9,
    totalTrips: 960,
    isVerified: true,
    ratingCategory: 'Gold',
  },
  {
    id: 'car-04',
    name: 'Sahara Cold-Chain Logistics',
    nameAr: 'الصحراء للنقل المبرد وسلاسل الإمداد',
    email: 'reefer@saharacold.sd',
    phone: '+249 912 300 440',
    city: 'Khartoum',
    fleetCount: 16,
    activeTrips: 6,
    trustScore: 92,
    onTimeDeliveryRate: 94.0,
    cancellationRate: 1.5,
    damageRate: 0.2,
    totalTrips: 630,
    isVerified: true,
    ratingCategory: 'Gold',
  },
  {
    id: 'car-05',
    name: 'Savannah Fast Cargo',
    nameAr: 'سافانا للشحن السريع',
    email: 'contact@savannahcargo.sd',
    phone: '+249 912 300 550',
    city: 'Atbara',
    fleetCount: 12,
    activeTrips: 5,
    trustScore: 84,
    onTimeDeliveryRate: 88.5,
    cancellationRate: 3.4,
    damageRate: 1.2,
    totalTrips: 410,
    isVerified: true,
    ratingCategory: 'Silver',
  },
];

export const mockDrivers: Driver[] = [
  {
    id: 'drv-01',
    name: 'Osman Abdelrahman Hassan',
    nameAr: 'عثمان عبد الرحمن حسن',
    phone: '+249 911 880 101',
    carrierId: 'car-01',
    carrierName: 'Nile Express',
    licenseNumber: 'SD-KRT-88491',
    licenseExpiry: '2027-11-15',
    trustScore: 98,
    status: 'on_trip',
    rating: 4.9,
    totalTrips: 340,
    onTimeRate: 98.2,
    currentVehiclePlate: 'KRT-9412-TRK',
    currentLocation: 'Km 310, Khartoum - Port Sudan Hwy',
    currentLat: 17.65,
    currentLng: 35.12,
    walletBalance: 485000,
  },
  {
    id: 'drv-02',
    name: 'Tariq Al-Bashir Omer',
    nameAr: 'طارق البشير عمر',
    phone: '+249 911 880 102',
    carrierId: 'car-02',
    carrierName: 'Red Sea Freight',
    licenseNumber: 'SD-PSD-30219',
    licenseExpiry: '2026-09-20',
    trustScore: 95,
    status: 'on_trip',
    rating: 4.8,
    totalTrips: 410,
    onTimeRate: 96.5,
    currentVehiclePlate: 'PSD-1104-REEF',
    currentLocation: 'Hayya Junction Checkpoint',
    currentLat: 18.33,
    currentLng: 36.35,
    walletBalance: 620000,
  },
  {
    id: 'drv-03',
    name: 'Mahmoud Idris Bakri',
    nameAr: 'محمود إدريس بكري',
    phone: '+249 911 880 103',
    carrierId: 'car-02',
    carrierName: 'Red Sea Freight',
    licenseNumber: 'SD-PSD-77412',
    licenseExpiry: '2028-02-10',
    trustScore: 93,
    status: 'available',
    rating: 4.7,
    totalTrips: 215,
    onTimeRate: 94.1,
    currentVehiclePlate: 'PSD-6029-FLAT',
    currentLocation: 'Port Sudan South Gate Logistics Yard',
    currentLat: 19.58,
    currentLng: 37.21,
    walletBalance: 310000,
  },
  {
    id: 'drv-04',
    name: 'Mustafa El-Hadi Ali',
    nameAr: 'مصطفى الهادي علي',
    phone: '+249 911 880 104',
    carrierId: 'car-03',
    carrierName: 'Blue Nile Transport',
    licenseNumber: 'SD-MDN-55102',
    licenseExpiry: '2027-06-18',
    trustScore: 91,
    status: 'on_trip',
    rating: 4.6,
    totalTrips: 180,
    onTimeRate: 92.4,
    currentVehiclePlate: 'MDN-4421-TRK',
    currentLocation: 'Gedaref - Wad Madani Corridor',
    currentLat: 14.15,
    currentLng: 34.85,
    walletBalance: 290000,
  },
  {
    id: 'drv-05',
    name: 'Ahmed Babiker Zain',
    nameAr: 'أحمد بابكر زين',
    phone: '+249 911 880 105',
    carrierId: 'car-04',
    carrierName: 'Sahara Cold-Chain',
    licenseNumber: 'SD-KRT-12994',
    licenseExpiry: '2026-12-05',
    trustScore: 96,
    status: 'available',
    rating: 4.9,
    totalTrips: 290,
    onTimeRate: 97.0,
    currentVehiclePlate: 'KRT-7730-REEF',
    currentLocation: 'Khartoum Industrial Cold Store Area',
    currentLat: 15.55,
    currentLng: 32.53,
    walletBalance: 540000,
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-01',
    plateNumber: 'KRT-9412-TRK',
    carrierId: 'car-01',
    carrierName: 'Nile Express',
    type: 'truck_heavy',
    makeModel: 'Mercedes-Benz Actros 3345',
    year: 2023,
    capacityTons: 32,
    status: 'in_transit',
    driverId: 'drv-01',
    driverName: 'عثمان عبد الرحمن',
    currentLat: 17.65,
    currentLng: 35.12,
    currentCity: 'Between Atbara & Sinkat',
    heading: 48,
    speedKmh: 68,
    fuelLevelPercent: 74,
    mileageKm: 84200,
    nextMaintenanceKm: 90000,
    isReturningEmpty: false,
  },
  {
    id: 'veh-02',
    plateNumber: 'PSD-1104-REEF',
    carrierId: 'car-02',
    carrierName: 'Red Sea Freight',
    type: 'reefer',
    makeModel: 'Volvo FH16 ThermoKing',
    year: 2024,
    capacityTons: 26,
    status: 'in_transit',
    driverId: 'drv-02',
    driverName: 'طارق البشير',
    currentLat: 18.33,
    currentLng: 36.35,
    currentCity: 'Hayya Junction',
    heading: 62,
    speedKmh: 72,
    fuelLevelPercent: 81,
    mileageKm: 42100,
    nextMaintenanceKm: 55000,
    isReturningEmpty: false,
  },
  {
    id: 'veh-03',
    plateNumber: 'PSD-6029-FLAT',
    carrierId: 'car-02',
    carrierName: 'Red Sea Freight',
    type: 'flatbed',
    makeModel: 'Scania R500 Flatbed',
    year: 2022,
    capacityTons: 35,
    status: 'returning_empty',
    driverId: 'drv-03',
    driverName: 'محمود إدريس',
    currentLat: 19.61,
    currentLng: 37.21,
    currentCity: 'Port Sudan',
    heading: 230,
    speedKmh: 0,
    fuelLevelPercent: 92,
    mileageKm: 118400,
    nextMaintenanceKm: 125000,
    isReturningEmpty: true,
    emptyReturnOrigin: 'Port Sudan',
    emptyReturnDestination: 'Khartoum',
  },
  {
    id: 'veh-04',
    plateNumber: 'MDN-4421-TRK',
    carrierId: 'car-03',
    carrierName: 'Blue Nile Transport',
    type: 'truck_heavy',
    makeModel: 'MAN TGS 33.480',
    year: 2023,
    capacityTons: 30,
    status: 'in_transit',
    driverId: 'drv-04',
    driverName: 'مصطفى الهادي',
    currentLat: 14.15,
    currentLng: 34.85,
    currentCity: 'Gedaref Suburbs',
    heading: 310,
    speedKmh: 64,
    fuelLevelPercent: 62,
    mileageKm: 76500,
    nextMaintenanceKm: 80000,
    isReturningEmpty: false,
  },
  {
    id: 'veh-05',
    plateNumber: 'KRT-7730-REEF',
    carrierId: 'car-04',
    carrierName: 'Sahara Cold-Chain',
    type: 'reefer',
    makeModel: 'DAF XF 480 Pure Cold',
    year: 2024,
    capacityTons: 24,
    status: 'available',
    driverId: 'drv-05',
    driverName: 'أحمد بابكر',
    currentLat: 15.55,
    currentLng: 32.53,
    currentCity: 'Khartoum',
    heading: 0,
    speedKmh: 0,
    fuelLevelPercent: 88,
    mileageKm: 31200,
    nextMaintenanceKm: 45000,
    isReturningEmpty: false,
  },
  {
    id: 'veh-06',
    plateNumber: 'ATB-3091-TANK',
    carrierId: 'car-05',
    carrierName: 'Savannah Fast Cargo',
    type: 'tanker',
    makeModel: 'Mercedes Arocs 3342 Tanker',
    year: 2022,
    capacityTons: 34,
    status: 'returning_empty',
    currentLat: 17.7,
    currentLng: 33.98,
    currentCity: 'Atbara',
    heading: 195,
    speedKmh: 45,
    fuelLevelPercent: 55,
    mileageKm: 142000,
    nextMaintenanceKm: 150000,
    isReturningEmpty: true,
    emptyReturnOrigin: 'Atbara Cement Plants',
    emptyReturnDestination: 'Port Sudan Fuel Terminals',
  },
];

export const mockShipments: Shipment[] = [
  {
    id: 'shp-001',
    trackingNumber: 'SDN-88419',
    customerName: 'DAL Food Industrial Group',
    customerNameAr: 'مجموعة دال الغذائية والصناعية',
    customerId: 'cust-dal',
    status: 'in_transit',
    cargoType: 'bulk',
    cargoDescription: 'Wheat Flour & Bakery Supplies (650 Bags)',
    totalWeightKg: 28000,
    totalVolumeM3: 42,
    origin: {
      city: 'Khartoum North',
      country: 'Sudan',
      address: 'Sayga Flour Mills Complex, North Industrial',
      lat: 15.65,
      lng: 32.55,
      contactName: 'Eng. Adil El-Mardi',
      contactPhone: '+249 912 110 011',
    },
    destination: {
      city: 'Port Sudan',
      country: 'Sudan',
      address: 'Red Sea Central Distribution Hub, Gate 4',
      lat: 19.61,
      lng: 37.21,
      contactName: 'Ustaz Sami Hamad',
      contactPhone: '+249 912 110 022',
    },
    pickupDate: '2026-08-21 08:30',
    deliveryDate: '2026-08-22 17:00',
    requiredVehicleType: 'truck_heavy',
    carrierId: 'car-01',
    carrierName: 'Nile Express',
    driverId: 'drv-01',
    driverName: 'عثمان عبد الرحمن حسن',
    driverPhone: '+249 911 880 101',
    vehicleId: 'veh-01',
    vehiclePlate: 'KRT-9412-TRK',
    currentLat: 17.65,
    currentLng: 35.12,
    price: 3450000,
    currency: 'SDG',
    distanceKm: 830,
    estimatedEta: '16:45 (Today)',
    etaConfidence: 94,
    priority: 'express',
    isFragile: false,
    isTempControlled: false,
    hasInsurance: true,
    podOtp: '749102',
    events: [
      {
        id: 'ev-1',
        timestamp: '2026-08-21 07:00',
        status: 'confirmed',
        titleAr: 'تم تأكيد طلب الشحن وتعيين الناقل',
        titleEn: 'Shipment Confirmed & Carrier Assigned',
        descriptionAr: 'تم حجز مركبة ثقيلة تابعة لشركة نيل إكسبريس',
        descriptionEn: 'Nile Express heavy truck assigned with verified SLA',
      },
      {
        id: 'ev-2',
        timestamp: '2026-08-21 08:45',
        status: 'loading',
        titleAr: 'اكتمال التحميل ومطابقة البوالص',
        titleEn: 'Loading Complete & Manifest Verified',
        descriptionAr: 'تم فحص أوزان الشحنة والأختام الرقمية بنجاح',
        descriptionEn: 'Digital weight inspection and seals successfully locked',
      },
      {
        id: 'ev-3',
        timestamp: '2026-08-21 09:30',
        status: 'in_transit',
        titleAr: 'انطلاق الشاحنة على طريق التحدي',
        titleEn: 'En Route on Al-Tahaddi Highway',
        descriptionAr: 'مرور الشاحنة بنقطة تفتيش الجيلي باتجاه شندي',
        descriptionEn: 'Passed Al-Jaili checkpoint heading towards Shendi',
      },
      {
        id: 'ev-4',
        timestamp: '2026-08-22 04:10',
        status: 'in_transit',
        titleAr: 'عبور ممر هيا باتجاه سواكن وبورتسودان',
        titleEn: 'Transit Hayya Pass toward Sawakin & Port Sudan',
        descriptionAr: 'السرعة منتظمة والـ GPS متصل بكفاءة 100%',
        descriptionEn: 'Smooth transit, GPS signal live at 100% fidelity',
      },
    ],
    backhaulMatched: false,
  },
  {
    id: 'shp-002',
    trackingNumber: 'SDN-99104',
    customerName: 'Sudan National Medical Supplies Fund',
    customerNameAr: 'الصندوق القومي للإمدادات الطبية',
    customerId: 'cust-nmsf',
    status: 'in_transit',
    cargoType: 'pharmaceuticals',
    cargoDescription: 'Essential Insulin & Vaccines (+2°C to +8°C)',
    totalWeightKg: 14500,
    totalVolumeM3: 28,
    origin: {
      city: 'Port Sudan Seaport Terminal',
      country: 'Sudan',
      address: 'Cold Storage Berth #7, Port Sudan Free Zone',
      lat: 19.62,
      lng: 37.22,
      contactName: 'Dr. Fatima El-Nour',
      contactPhone: '+249 912 440 011',
    },
    destination: {
      city: 'Khartoum Central Medical Stores',
      country: 'Sudan',
      address: 'Central Medical Supplies Depot, Al-Mogran',
      lat: 15.59,
      lng: 32.51,
      contactName: 'Dr. Yasser Zein',
      contactPhone: '+249 912 440 022',
    },
    pickupDate: '2026-08-21 18:00',
    deliveryDate: '2026-08-22 14:00',
    requiredVehicleType: 'reefer',
    carrierId: 'car-02',
    carrierName: 'Red Sea Freight',
    driverId: 'drv-02',
    driverName: 'طارق البشير عمر',
    driverPhone: '+249 911 880 102',
    vehicleId: 'veh-02',
    vehiclePlate: 'PSD-1104-REEF',
    currentLat: 18.33,
    currentLng: 36.35,
    price: 5200000,
    currency: 'SDG',
    distanceKm: 840,
    estimatedEta: '13:30 (Today)',
    etaConfidence: 96,
    priority: 'critical',
    isFragile: true,
    isTempControlled: true,
    targetTemp: 4.2,
    hasInsurance: true,
    podOtp: '318904',
    events: [
      {
        id: 'ev-10',
        timestamp: '2026-08-21 16:30',
        status: 'confirmed',
        titleAr: 'تأكيد شحنة أدوية طارئة مبردة',
        titleEn: 'Cold-Chain Urgent Medical Shipment Locked',
        descriptionAr: 'فحص مسبق لدرجات حرارة الحاوية (-20 إلى +4)',
        descriptionEn: 'Pre-cooling chamber calibrated at 4.0°C',
      },
      {
        id: 'ev-11',
        timestamp: '2026-08-21 19:00',
        status: 'in_transit',
        titleAr: 'انطلاق الشاحنة من ميناء بورتسودان',
        titleEn: 'Departed Port Sudan Cold Quay',
        descriptionAr: 'درجة حرارة الحساس: 4.2°C مستقرة تماماً',
        descriptionEn: 'Telemetry temp steady at 4.2°C, full battery backup',
      },
    ],
    backhaulMatched: false,
  },
  {
    id: 'shp-003',
    trackingNumber: 'SDN-77312',
    customerName: 'Kenana Sugar Company Ltd.',
    customerNameAr: 'شركة سكر كنانة المحدودة',
    customerId: 'cust-kenana',
    status: 'awaiting_carrier',
    cargoType: 'bulk',
    cargoDescription: 'Refined White Sugar for Export (30 MT)',
    totalWeightKg: 30000,
    totalVolumeM3: 45,
    origin: {
      city: 'Kenana Factory Area',
      country: 'Sudan',
      address: 'Main Silos & Packaging Plant, White Nile',
      lat: 13.16,
      lng: 32.66,
      contactName: 'Eng. Babiker Rahma',
      contactPhone: '+249 912 550 099',
    },
    destination: {
      city: 'Port Sudan Export Quay',
      country: 'Sudan',
      address: 'Grain & Bulk Export Terminal Berth 14',
      lat: 19.6,
      lng: 37.23,
      contactName: 'Capt. Gamal Baraka',
      contactPhone: '+249 912 550 088',
    },
    pickupDate: '2026-08-23 09:00',
    deliveryDate: '2026-08-25 12:00',
    requiredVehicleType: 'flatbed',
    price: 4100000,
    currency: 'SDG',
    distanceKm: 1120,
    estimatedEta: '26h Transit Time',
    etaConfidence: 89,
    priority: 'normal',
    isFragile: false,
    isTempControlled: false,
    hasInsurance: true,
    events: [
      {
        id: 'ev-20',
        timestamp: '2026-08-22 00:15',
        status: 'quote_requested',
        titleAr: 'طلب سعر وشاحنة لشحنة تصدير كنانة',
        titleEn: 'Export Cargo Load Posted on Exchange',
        descriptionAr: 'في انتظار مطابقة أفضل ناقل عبر محرك الذكاء الاصطناعي',
        descriptionEn: 'Broadcasting to Platinum Carriers with Empty-Truck Optimization',
      },
    ],
    backhaulMatched: true,
  },
  {
    id: 'shp-004',
    trackingNumber: 'SDN-66290',
    customerName: 'Gedaref Agricultural Export Consortium',
    customerNameAr: 'تجمع مصدري محاصيل القضارف والسمسم',
    customerId: 'cust-gedaref',
    status: 'in_transit',
    cargoType: 'bulk',
    cargoDescription: 'Premium Grade Sesame Seeds (800 Jute Sacks)',
    totalWeightKg: 29500,
    totalVolumeM3: 40,
    origin: {
      city: 'Gedaref Crop Market',
      country: 'Sudan',
      address: 'Al-Gedaref Central Agricultural Market, Warehouse 12',
      lat: 14.03,
      lng: 35.38,
      contactName: 'El-Sayed Abdelkarim',
      contactPhone: '+249 912 770 011',
    },
    destination: {
      city: 'Port Sudan Export Terminal',
      country: 'Sudan',
      address: 'Agricultural Inspection & Export Pier',
      lat: 19.61,
      lng: 37.21,
      contactName: 'Customs Officer Khalid',
      contactPhone: '+249 912 770 022',
    },
    pickupDate: '2026-08-21 14:00',
    deliveryDate: '2026-08-23 09:00',
    requiredVehicleType: 'truck_heavy',
    carrierId: 'car-03',
    carrierName: 'Blue Nile Transport',
    driverId: 'drv-04',
    driverName: 'مصطفى الهادي علي',
    driverPhone: '+249 911 880 104',
    vehicleId: 'veh-04',
    vehiclePlate: 'MDN-4421-TRK',
    currentLat: 14.15,
    currentLng: 34.85,
    price: 3800000,
    currency: 'SDG',
    distanceKm: 760,
    estimatedEta: '07:15 (Tomorrow)',
    etaConfidence: 91,
    priority: 'normal',
    isFragile: false,
    isTempControlled: false,
    hasInsurance: true,
    podOtp: '992014',
    events: [],
    backhaulMatched: false,
  },
  {
    id: 'shp-005',
    trackingNumber: 'SDN-55102',
    customerName: 'GIAD Engineering & Industrial Hub',
    customerNameAr: 'مجموعة جياد للصناعات الهندسية',
    customerId: 'cust-giad',
    status: 'delivered',
    cargoType: 'heavy_machinery',
    cargoDescription: 'Hydraulic Press & Automotive Components',
    totalWeightKg: 22000,
    totalVolumeM3: 36,
    origin: {
      city: 'Port Sudan Sea Gateway',
      country: 'Sudan',
      address: 'Heavy Lift Wharf #3',
      lat: 19.6,
      lng: 37.22,
    },
    destination: {
      city: 'GIAD Industrial City',
      country: 'Sudan',
      address: 'Automotive Plant #2, South Khartoum Km 50',
      lat: 15.22,
      lng: 32.88,
    },
    pickupDate: '2026-08-19 10:00',
    deliveryDate: '2026-08-21 16:30',
    requiredVehicleType: 'flatbed',
    carrierId: 'car-01',
    carrierName: 'Nile Express',
    price: 4900000,
    currency: 'SDG',
    distanceKm: 890,
    estimatedEta: 'Delivered On Time',
    etaConfidence: 100,
    priority: 'express',
    isFragile: true,
    isTempControlled: false,
    hasInsurance: true,
    podVerifiedAt: '2026-08-21 16:35',
    events: [],
    backhaulMatched: true,
  },
];

export const mockBackhaulOpportunities: BackhaulOpportunity[] = [
  {
    id: 'bh-01',
    vehicleId: 'veh-03',
    vehiclePlate: 'PSD-6029-FLAT',
    driverName: 'محمود إدريس بكري',
    driverPhone: '+249 911 880 103',
    carrierName: 'Red Sea Freight',
    currentCity: 'Port Sudan',
    targetCity: 'Khartoum',
    availableCapacityTons: 35,
    availableDate: '2026-08-22 14:00 (Today)',
    detourDistanceKm: 12,
    backhaulScore: 98,
    discountPercent: 28, // Customer saves 28%
    expectedProfitIncrease: 1950000, // Carrier earns extra
    compatibleShipmentIds: ['shp-003'],
  },
  {
    id: 'bh-02',
    vehicleId: 'veh-06',
    vehiclePlate: 'ATB-3091-TANK',
    driverName: 'سائق شاحنة صهريج',
    driverPhone: '+249 911 880 106',
    carrierName: 'Savannah Fast Cargo',
    currentCity: 'Atbara',
    targetCity: 'Port Sudan',
    availableCapacityTons: 34,
    availableDate: '2026-08-22 18:00',
    detourDistanceKm: 18,
    backhaulScore: 92,
    discountPercent: 22,
    expectedProfitIncrease: 1400000,
    compatibleShipmentIds: [],
  },
  {
    id: 'bh-03',
    vehicleId: 'veh-05',
    vehiclePlate: 'KRT-7730-REEF',
    driverName: 'أحمد بابكر زين',
    driverPhone: '+249 911 880 105',
    carrierName: 'Sahara Cold-Chain',
    currentCity: 'Khartoum',
    targetCity: 'Wad Madani & Sennar',
    availableCapacityTons: 24,
    availableDate: '2026-08-23 07:00',
    detourDistanceKm: 8,
    backhaulScore: 94,
    discountPercent: 25,
    expectedProfitIncrease: 980000,
    compatibleShipmentIds: [],
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-01',
    incidentNumber: 'INC-2026-08-01',
    shipmentId: 'shp-001',
    trackingNumber: 'SDN-88419',
    driverName: 'عثمان عبد الرحمن',
    vehiclePlate: 'KRT-9412-TRK',
    severity: 'medium',
    type: 'security_checkpoint',
    titleAr: 'تأخير مؤقت بنقطة تفتيش جمركية قرب شندي',
    titleEn: 'Temporary customs security inspection hold',
    description: 'إعادة مطابقة باركود الحاويات مع نظام سيكودا الجمركي — التأخير المتوقع 45 دقيقة فقط',
    location: 'Km 185, Al-Tahaddi Hwy',
    lat: 16.7,
    lng: 33.42,
    status: 'investigating',
    createdAt: '2026-08-22 00:30',
  },
  {
    id: 'inc-02',
    incidentNumber: 'INC-2026-08-02',
    severity: 'high',
    type: 'breakdown',
    titleAr: 'عطل في مضخة وقود لشاحنة غير معينة',
    titleEn: 'Fuel injector breakdown alert',
    description: 'تم توجيه أقرب فريق صيانة متنقل من محطة هيا',
    location: 'Hayya Summit Pass, Km 520',
    lat: 18.2,
    lng: 36.1,
    status: 'rescue_dispatched',
    createdAt: '2026-08-21 22:15',
    rescueVehicleAssigned: 'PSD-9011-SERVICE',
    rescueEta: '25 mins',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'INV-2026-0891',
    shipmentId: 'shp-005',
    trackingNumber: 'SDN-55102',
    customerName: 'GIAD Engineering Hub',
    customerNameAr: 'مجموعة جياد الهندسية',
    amount: 4900000,
    tax: 0,
    total: 4900000,
    currency: 'SDG',
    status: 'paid',
    issueDate: '2026-08-21',
    dueDate: '2026-09-20',
    paidAt: '2026-08-21 17:00',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'INV-2026-0892',
    shipmentId: 'shp-001',
    trackingNumber: 'SDN-88419',
    customerName: 'DAL Food Industrial Group',
    customerNameAr: 'مجموعة دال الغذائية',
    amount: 3450000,
    tax: 0,
    total: 3450000,
    currency: 'SDG',
    status: 'pending',
    issueDate: '2026-08-21',
    dueDate: '2026-09-21',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'INV-2026-0893',
    shipmentId: 'shp-002',
    trackingNumber: 'SDN-99104',
    customerName: 'National Medical Supplies Fund',
    customerNameAr: 'الصندوق القومي للإمدادات الطبية',
    amount: 5200000,
    tax: 0,
    total: 5200000,
    currency: 'SDG',
    status: 'pending',
    issueDate: '2026-08-21',
    dueDate: '2026-09-21',
  },
];

export const mockWalletTransactions: WalletTransaction[] = [
  {
    id: 'tx-01',
    type: 'settlement',
    amount: 4410000,
    currency: 'SDG',
    status: 'completed',
    date: '2026-08-21 17:05',
    descriptionAr: 'تسوية تسليم شحنة جياد #SDN-55102 بعد مطابقة الـ POD',
    descriptionEn: 'Automated POD Release Settlement for SDN-55102',
    referenceShipment: 'SDN-55102',
  },
  {
    id: 'tx-02',
    type: 'fee',
    amount: 490000,
    currency: 'SDG',
    status: 'completed',
    date: '2026-08-21 17:05',
    descriptionAr: 'عمولة منصة سودانيل الذكية (10%)',
    descriptionEn: 'Sudaneel Platform Exchange Fee (10%)',
    referenceShipment: 'SDN-55102',
  },
  {
    id: 'tx-03',
    type: 'credit',
    amount: 10000000,
    currency: 'SDG',
    status: 'completed',
    date: '2026-08-20 11:30',
    descriptionAr: 'شحن رصيد المحفظة عبر تحويل بنك الخرطوم (بنكك)',
    descriptionEn: 'Wallet Top-up via Bank of Khartoum (Bankak)',
  },
];
