// Inject new view sections into the dashboard
function injectNewSections(){
const target=document.querySelector('#view-settings');
if(!target)return;
const html=`
<!-- 6. Finance View -->
<div id="view-finance" class="view-section transition-all duration-300 hidden">
<div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10">
<div><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="الإدارة المالية والمحاسبة" data-en="Financial Management">الإدارة المالية والمحاسبة</h2>
<p class="lang-text font-body-md text-on-surface-variant font-medium" data-ar="إدارة الفواتير والإيرادات والمصروفات التشغيلية." data-en="Manage invoices, revenue, and operational expenses.">إدارة الفواتير والإيرادات والمصروفات التشغيلية.</p></div>
<button onclick="triggerToastAlert('تم إنشاء فاتورة جديدة','New invoice created')" class="flex items-center gap-2 px-6 py-3 bg-secondary-container text-on-secondary-container rounded-lg font-bold hover:bg-secondary-fixed transition-all active:scale-95 shadow-sm">
<span class="material-symbols-outlined">receipt_long</span><span class="lang-text font-label-md" data-ar="إصدار فاتورة جديدة" data-en="Issue New Invoice">إصدار فاتورة جديدة</span></button>
</div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-gutter mb-8">
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><div class="flex justify-between items-start mb-4"><div class="p-3 bg-secondary-fixed rounded-lg text-secondary"><span class="material-symbols-outlined">trending_up</span></div><span class="text-green-700 text-sm font-bold flex items-center gap-1"><span class="material-symbols-outlined text-sm">arrow_upward</span>+18.5%</span></div><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="إجمالي الإيرادات الشهرية" data-en="Monthly Revenue">إجمالي الإيرادات الشهرية</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">$128,400</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><div class="flex justify-between items-start mb-4"><div class="p-3 bg-secondary-fixed rounded-lg text-secondary"><span class="material-symbols-outlined">account_balance_wallet</span></div><span class="text-red-600 text-sm font-bold flex items-center gap-1"><span class="material-symbols-outlined text-sm">arrow_upward</span>+5.2%</span></div><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="المصروفات التشغيلية" data-en="Operating Expenses">المصروفات التشغيلية</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">$85,600</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><div class="flex justify-between items-start mb-4"><div class="p-3 bg-green-100 rounded-lg text-green-700"><span class="material-symbols-outlined">savings</span></div><span class="text-green-700 text-sm font-bold">33.3%</span></div><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="صافي الأرباح" data-en="Net Profit">صافي الأرباح</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">$42,800</p></div>
</div>
<section class="bg-surface-container-lowest rounded-xl border border-outline-variant industrial-shadow overflow-hidden">
<div class="p-6 border-b border-outline-variant flex justify-between items-center"><h3 class="lang-text font-headline-md text-primary" data-ar="الفواتير النشطة" data-en="Active Invoices">الفواتير النشطة</h3></div>
<div class="overflow-x-auto"><table class="w-full text-right border-collapse"><thead><tr class="bg-surface-container-low text-on-surface font-bold font-label-md border-b border-outline">
<th class="lang-text p-4" data-ar="رقم الفاتورة" data-en="Invoice #">رقم الفاتورة</th><th class="lang-text p-4" data-ar="العميل" data-en="Client">العميل</th><th class="lang-text p-4" data-ar="المبلغ" data-en="Amount">المبلغ</th><th class="lang-text p-4" data-ar="تاريخ الاستحقاق" data-en="Due Date">تاريخ الاستحقاق</th><th class="lang-text p-4" data-ar="الحالة" data-en="Status">الحالة</th></tr></thead>
<tbody class="divide-y divide-outline-variant">
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="p-4 font-bold text-primary">#INV-2041</td><td class="lang-text p-4 font-medium" data-ar="شركة النيل العالمية" data-en="Nile Global Co.">شركة النيل العالمية</td><td class="p-4 font-bold">$12,400</td><td class="p-4">2024-11-25</td><td class="p-4"><span class="lang-text px-3 py-1 bg-green-100 text-green-900 text-xs rounded-full font-bold" data-ar="مدفوعة" data-en="Paid">مدفوعة</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="p-4 font-bold text-primary">#INV-2042</td><td class="lang-text p-4 font-medium" data-ar="مجموعة الفجر للتجارة" data-en="Al-Fajr Trading Group">مجموعة الفجر للتجارة</td><td class="p-4 font-bold">$8,750</td><td class="p-4">2024-11-28</td><td class="p-4"><span class="lang-text px-3 py-1 bg-amber-100 text-amber-900 text-xs rounded-full font-bold" data-ar="معلقة" data-en="Pending">معلقة</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="p-4 font-bold text-primary">#INV-2038</td><td class="lang-text p-4 font-medium" data-ar="شركة البركة للاستيراد" data-en="Al-Baraka Import Co.">شركة البركة للاستيراد</td><td class="p-4 font-bold">$22,100</td><td class="p-4">2024-11-15</td><td class="p-4"><span class="lang-text px-3 py-1 bg-red-100 text-red-900 text-xs rounded-full font-bold" data-ar="متأخرة" data-en="Overdue">متأخرة</span></td></tr>
</tbody></table></div></section>
</div>

<!-- 7. Fleet View -->
<div id="view-fleet" class="view-section transition-all duration-300 hidden">
<div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10">
<div><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="إدارة الأسطول والمركبات" data-en="Fleet & Vehicle Management">إدارة الأسطول والمركبات</h2>
<p class="lang-text font-body-md text-on-surface-variant font-medium" data-ar="متابعة حالة المركبات والصيانة وكفاءة الأسطول." data-en="Track vehicle status, maintenance, and fleet efficiency.">متابعة حالة المركبات والصيانة وكفاءة الأسطول.</p></div>
<button onclick="triggerToastAlert('تمت إضافة المركبة','Vehicle added')" class="flex items-center gap-2 px-6 py-3 bg-secondary-container text-on-secondary-container rounded-lg font-bold hover:bg-secondary-fixed transition-all active:scale-95"><span class="material-symbols-outlined">add_circle</span><span class="lang-text font-label-md" data-ar="إضافة مركبة" data-en="Add Vehicle">إضافة مركبة</span></button></div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-gutter mb-8">
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><div class="flex justify-between items-start mb-4"><div class="p-3 bg-secondary-fixed rounded-lg text-secondary"><span class="material-symbols-outlined">local_shipping</span></div></div><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="المركبات النشطة" data-en="Active Vehicles">المركبات النشطة</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">42</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><div class="flex justify-between items-start mb-4"><div class="p-3 bg-amber-100 rounded-lg text-amber-700"><span class="material-symbols-outlined">build</span></div></div><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="قيد الصيانة" data-en="Under Maintenance">قيد الصيانة</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">6</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><div class="flex justify-between items-start mb-4"><div class="p-3 bg-green-100 rounded-lg text-green-700"><span class="material-symbols-outlined">local_gas_station</span></div></div><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="كفاءة الوقود" data-en="Fuel Efficiency">كفاءة الوقود</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">8.2 <span class="lang-text text-xl font-normal" data-ar="كم/لتر" data-en="km/L">كم/لتر</span></p></div>
</div>
<section class="bg-surface-container-lowest rounded-xl border border-outline-variant industrial-shadow overflow-hidden">
<div class="p-6 border-b border-outline-variant"><h3 class="lang-text font-headline-md text-primary" data-ar="سجل الأسطول" data-en="Fleet Registry">سجل الأسطول</h3></div>
<div class="overflow-x-auto"><table class="w-full text-right border-collapse"><thead><tr class="bg-surface-container-low text-on-surface font-bold font-label-md border-b border-outline">
<th class="lang-text p-4" data-ar="رقم المركبة" data-en="Vehicle #">رقم المركبة</th><th class="lang-text p-4" data-ar="النوع" data-en="Type">النوع</th><th class="lang-text p-4" data-ar="السائق" data-en="Driver">السائق</th><th class="lang-text p-4" data-ar="آخر موقع" data-en="Last Location">آخر موقع</th><th class="lang-text p-4" data-ar="الحالة" data-en="Status">الحالة</th></tr></thead>
<tbody class="divide-y divide-outline-variant">
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="p-4 font-bold text-primary">TRK-001</td><td class="lang-text p-4" data-ar="شاحنة ثقيلة" data-en="Heavy Truck">شاحنة ثقيلة</td><td class="lang-text p-4 font-medium" data-ar="محمد عبدالله" data-en="Mohammed Abdullah">محمد عبدالله</td><td class="lang-text p-4" data-ar="الخرطوم شمال" data-en="Khartoum North">الخرطوم شمال</td><td class="p-4"><span class="lang-text px-3 py-1 bg-green-100 text-green-900 text-xs rounded-full font-bold" data-ar="نشط" data-en="Active">نشط</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="p-4 font-bold text-primary">TRK-007</td><td class="lang-text p-4" data-ar="مقطورة" data-en="Trailer">مقطورة</td><td class="lang-text p-4 font-medium" data-ar="أحمد إبراهيم" data-en="Ahmed Ibrahim">أحمد إبراهيم</td><td class="lang-text p-4" data-ar="بورتسودان" data-en="Port Sudan">بورتسودان</td><td class="p-4"><span class="lang-text px-3 py-1 bg-amber-100 text-amber-900 text-xs rounded-full font-bold" data-ar="صيانة" data-en="Maintenance">صيانة</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="p-4 font-bold text-primary">PKP-012</td><td class="lang-text p-4" data-ar="بكب توصيل" data-en="Pickup">بكب توصيل</td><td class="lang-text p-4 font-medium" data-ar="عمر حسن" data-en="Omar Hassan">عمر حسن</td><td class="lang-text p-4" data-ar="مدني" data-en="Madani">مدني</td><td class="p-4"><span class="lang-text px-3 py-1 bg-green-100 text-green-900 text-xs rounded-full font-bold" data-ar="نشط" data-en="Active">نشط</span></td></tr>
</tbody></table></div></section>
</div>

<!-- 8. Customers View -->
<div id="view-customers" class="view-section transition-all duration-300 hidden">
<div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10">
<div><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="العملاء والشركاء" data-en="Customers & Partners">العملاء والشركاء</h2>
<p class="lang-text font-body-md text-on-surface-variant font-medium" data-ar="إدارة قاعدة العملاء وشركاء الشحن." data-en="Manage customer base and shipping partners.">إدارة قاعدة العملاء وشركاء الشحن.</p></div>
<button onclick="triggerToastAlert('تمت إضافة العميل','Customer added')" class="flex items-center gap-2 px-6 py-3 bg-secondary-container text-on-secondary-container rounded-lg font-bold hover:bg-secondary-fixed transition-all active:scale-95"><span class="material-symbols-outlined">person_add</span><span class="lang-text font-label-md" data-ar="إضافة عميل" data-en="Add Customer">إضافة عميل</span></button></div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-gutter mb-8">
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="العملاء النشطون" data-en="Active Customers">العملاء النشطون</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">248</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="شركاء الشحن" data-en="Shipping Partners">شركاء الشحن</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">34</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="رضا العملاء" data-en="Customer Satisfaction">رضا العملاء</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">96.4%</p></div>
</div>
<section class="bg-surface-container-lowest rounded-xl border border-outline-variant industrial-shadow overflow-hidden">
<div class="p-6 border-b border-outline-variant"><h3 class="lang-text font-headline-md text-primary" data-ar="سجل العملاء" data-en="Customer Registry">سجل العملاء</h3></div>
<div class="overflow-x-auto"><table class="w-full text-right border-collapse"><thead><tr class="bg-surface-container-low text-on-surface font-bold font-label-md border-b border-outline">
<th class="lang-text p-4" data-ar="العميل" data-en="Customer">العميل</th><th class="lang-text p-4" data-ar="الشركة" data-en="Company">الشركة</th><th class="lang-text p-4" data-ar="الشحنات" data-en="Shipments">الشحنات</th><th class="lang-text p-4" data-ar="إجمالي المدفوعات" data-en="Total Payments">إجمالي المدفوعات</th><th class="lang-text p-4" data-ar="التصنيف" data-en="Tier">التصنيف</th></tr></thead>
<tbody class="divide-y divide-outline-variant">
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="lang-text p-4 font-bold text-primary" data-ar="خالد المنصور" data-en="Khalid Al-Mansour">خالد المنصور</td><td class="lang-text p-4" data-ar="شركة النيل العالمية" data-en="Nile Global Co.">شركة النيل العالمية</td><td class="p-4 font-bold">142</td><td class="p-4 font-bold">$284,000</td><td class="p-4"><span class="px-3 py-1 bg-secondary-container text-on-secondary-container text-xs rounded-full font-bold">VIP</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="lang-text p-4 font-bold text-primary" data-ar="سارة أحمد" data-en="Sara Ahmed">سارة أحمد</td><td class="lang-text p-4" data-ar="مجموعة الفجر" data-en="Al-Fajr Group">مجموعة الفجر</td><td class="p-4 font-bold">67</td><td class="p-4 font-bold">$98,500</td><td class="p-4"><span class="lang-text px-3 py-1 bg-surface-container text-primary text-xs rounded-full font-bold" data-ar="عادي" data-en="Standard">عادي</span></td></tr>
</tbody></table></div></section>
</div>

<!-- 9. HR View -->
<div id="view-hr" class="view-section transition-all duration-300 hidden">
<div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10">
<div><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="الموارد البشرية" data-en="Human Resources">الموارد البشرية</h2>
<p class="lang-text font-body-md text-on-surface-variant font-medium" data-ar="إدارة الموظفين والحضور والإجازات." data-en="Manage employees, attendance, and leave.">إدارة الموظفين والحضور والإجازات.</p></div>
<button onclick="triggerToastAlert('تمت إضافة الموظف','Employee added')" class="flex items-center gap-2 px-6 py-3 bg-secondary-container text-on-secondary-container rounded-lg font-bold hover:bg-secondary-fixed transition-all active:scale-95"><span class="material-symbols-outlined">person_add</span><span class="lang-text font-label-md" data-ar="إضافة موظف" data-en="Add Employee">إضافة موظف</span></button></div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-gutter mb-8">
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="عدد الموظفين" data-en="Total Employees">عدد الموظفين</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">186</p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="الحضور اليومي" data-en="Daily Attendance">الحضور اليومي</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">172 <span class="text-green-700 text-sm font-bold">92%</span></p></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow"><h3 class="lang-text font-label-md text-on-surface-variant" data-ar="إجازات معلقة" data-en="Pending Leaves">إجازات معلقة</h3><p class="font-headline-xl text-headline-xl text-primary mt-1">8</p></div>
</div>
<section class="bg-surface-container-lowest rounded-xl border border-outline-variant industrial-shadow overflow-hidden">
<div class="p-6 border-b border-outline-variant"><h3 class="lang-text font-headline-md text-primary" data-ar="سجل الموظفين" data-en="Employee Registry">سجل الموظفين</h3></div>
<div class="overflow-x-auto"><table class="w-full text-right border-collapse"><thead><tr class="bg-surface-container-low text-on-surface font-bold font-label-md border-b border-outline">
<th class="lang-text p-4" data-ar="الموظف" data-en="Employee">الموظف</th><th class="lang-text p-4" data-ar="القسم" data-en="Department">القسم</th><th class="lang-text p-4" data-ar="المنصب" data-en="Position">المنصب</th><th class="lang-text p-4" data-ar="تاريخ التعيين" data-en="Hire Date">تاريخ التعيين</th><th class="lang-text p-4" data-ar="الحالة" data-en="Status">الحالة</th></tr></thead>
<tbody class="divide-y divide-outline-variant">
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="lang-text p-4 font-bold text-primary" data-ar="عادل محمد" data-en="Adel Mohammed">عادل محمد</td><td class="lang-text p-4" data-ar="العمليات" data-en="Operations">العمليات</td><td class="lang-text p-4" data-ar="مدير عمليات" data-en="Operations Manager">مدير عمليات</td><td class="p-4">2021-03-15</td><td class="p-4"><span class="lang-text px-3 py-1 bg-green-100 text-green-900 text-xs rounded-full font-bold" data-ar="نشط" data-en="Active">نشط</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="lang-text p-4 font-bold text-primary" data-ar="فاطمة علي" data-en="Fatima Ali">فاطمة علي</td><td class="lang-text p-4" data-ar="المالية" data-en="Finance">المالية</td><td class="lang-text p-4" data-ar="محاسبة أولى" data-en="Senior Accountant">محاسبة أولى</td><td class="p-4">2022-01-10</td><td class="p-4"><span class="lang-text px-3 py-1 bg-green-100 text-green-900 text-xs rounded-full font-bold" data-ar="نشط" data-en="Active">نشط</span></td></tr>
<tr class="hover:bg-surface-container-low transition-colors text-on-surface"><td class="lang-text p-4 font-bold text-primary" data-ar="يوسف حسين" data-en="Yousef Hussein">يوسف حسين</td><td class="lang-text p-4" data-ar="اللوجستيات" data-en="Logistics">اللوجستيات</td><td class="lang-text p-4" data-ar="منسق شحن" data-en="Shipping Coordinator">منسق شحن</td><td class="p-4">2023-06-20</td><td class="p-4"><span class="lang-text px-3 py-1 bg-amber-100 text-amber-900 text-xs rounded-full font-bold" data-ar="إجازة" data-en="On Leave">إجازة</span></td></tr>
</tbody></table></div></section>
</div>
`;
target.insertAdjacentHTML('afterend',html);
}
document.addEventListener('DOMContentLoaded',injectNewSections);
