// Inject Reports, Notifications, Profile, Support sections
function injectSystemSections(){
const hr=document.querySelector('#view-hr');
if(!hr)return;
const h=`
<div id="view-reports" class="view-section transition-all duration-300 hidden">
<div class="mb-10"><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="التقارير والتحليلات" data-en="Reports & Analytics">التقارير والتحليلات</h2>
<p class="lang-text font-body-md text-on-surface-variant font-medium" data-ar="تقارير شاملة لجميع العمليات اللوجستية." data-en="Comprehensive reports for all logistics operations.">تقارير شاملة لجميع العمليات اللوجستية.</p></div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-gutter">
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow hover:border-secondary transition-all cursor-pointer"><span class="material-symbols-outlined text-3xl text-secondary mb-3">local_shipping</span><h4 class="lang-text font-bold text-primary mb-1" data-ar="تقرير الشحنات" data-en="Shipments Report">تقرير الشحنات</h4><p class="lang-text text-xs text-on-surface-variant" data-ar="آخر تحديث: اليوم" data-en="Last update: Today">آخر تحديث: اليوم</p><div class="flex gap-2 mt-4"><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-secondary-container text-on-secondary-container text-xs rounded-lg font-bold">PDF</button><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-surface-container text-primary text-xs rounded-lg font-bold border border-outline-variant">Excel</button></div></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow hover:border-secondary transition-all cursor-pointer"><span class="material-symbols-outlined text-3xl text-secondary mb-3">inventory_2</span><h4 class="lang-text font-bold text-primary mb-1" data-ar="تقرير المخزون" data-en="Inventory Report">تقرير المخزون</h4><p class="lang-text text-xs text-on-surface-variant" data-ar="آخر تحديث: أمس" data-en="Last update: Yesterday">آخر تحديث: أمس</p><div class="flex gap-2 mt-4"><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-secondary-container text-on-secondary-container text-xs rounded-lg font-bold">PDF</button><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-surface-container text-primary text-xs rounded-lg font-bold border border-outline-variant">Excel</button></div></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow hover:border-secondary transition-all cursor-pointer"><span class="material-symbols-outlined text-3xl text-secondary mb-3">account_balance</span><h4 class="lang-text font-bold text-primary mb-1" data-ar="التقرير المالي" data-en="Financial Report">التقرير المالي</h4><p class="lang-text text-xs text-on-surface-variant" data-ar="آخر تحديث: اليوم" data-en="Last update: Today">آخر تحديث: اليوم</p><div class="flex gap-2 mt-4"><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-secondary-container text-on-secondary-container text-xs rounded-lg font-bold">PDF</button><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-surface-container text-primary text-xs rounded-lg font-bold border border-outline-variant">Excel</button></div></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow hover:border-secondary transition-all cursor-pointer"><span class="material-symbols-outlined text-3xl text-secondary mb-3">directions_car</span><h4 class="lang-text font-bold text-primary mb-1" data-ar="أداء الأسطول" data-en="Fleet Performance">أداء الأسطول</h4><p class="lang-text text-xs text-on-surface-variant" data-ar="آخر تحديث: أمس" data-en="Last update: Yesterday">آخر تحديث: أمس</p><div class="flex gap-2 mt-4"><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-secondary-container text-on-secondary-container text-xs rounded-lg font-bold">PDF</button><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-surface-container text-primary text-xs rounded-lg font-bold border border-outline-variant">Excel</button></div></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow hover:border-secondary transition-all cursor-pointer"><span class="material-symbols-outlined text-3xl text-secondary mb-3">verified</span><h4 class="lang-text font-bold text-primary mb-1" data-ar="التخليص الجمركي" data-en="Customs Report">التخليص الجمركي</h4><p class="lang-text text-xs text-on-surface-variant" data-ar="آخر تحديث: اليوم" data-en="Last update: Today">آخر تحديث: اليوم</p><div class="flex gap-2 mt-4"><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-secondary-container text-on-secondary-container text-xs rounded-lg font-bold">PDF</button><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-surface-container text-primary text-xs rounded-lg font-bold border border-outline-variant">Excel</button></div></div>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow hover:border-secondary transition-all cursor-pointer"><span class="material-symbols-outlined text-3xl text-secondary mb-3">assessment</span><h4 class="lang-text font-bold text-primary mb-1" data-ar="الأداء العام KPI" data-en="KPI Performance">الأداء العام KPI</h4><p class="lang-text text-xs text-on-surface-variant" data-ar="آخر تحديث: اليوم" data-en="Last update: Today">آخر تحديث: اليوم</p><div class="flex gap-2 mt-4"><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-secondary-container text-on-secondary-container text-xs rounded-lg font-bold">PDF</button><button onclick="triggerToastAlert('جاري التحميل...','Downloading...')" class="px-3 py-1.5 bg-surface-container text-primary text-xs rounded-lg font-bold border border-outline-variant">Excel</button></div></div>
</div></div>

<div id="view-notifications" class="view-section transition-all duration-300 hidden">
<div class="flex justify-between items-center mb-10"><div><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="مركز الإشعارات" data-en="Notifications Center">مركز الإشعارات</h2></div>
<button onclick="document.querySelectorAll('.notif-dot').forEach(d=>d.remove());document.getElementById('notif-badge').textContent='0';triggerToastAlert('تم تعليم الكل كمقروء','All marked as read')" class="lang-text px-4 py-2 bg-surface-container text-primary rounded-lg text-xs font-bold border border-outline-variant" data-ar="تعليم الكل كمقروء" data-en="Mark all read">تعليم الكل كمقروء</button></div>
<div class="space-y-3">
<div class="bg-surface-container-lowest p-5 rounded-xl border border-outline-variant industrial-shadow flex items-start gap-4"><div class="p-2 bg-secondary-fixed rounded-lg text-secondary"><span class="material-symbols-outlined">local_shipping</span></div><div class="flex-grow"><h4 class="lang-text font-bold text-primary text-sm" data-ar="شحنة #SD-9021 وصلت بورتسودان" data-en="Shipment #SD-9021 arrived Port Sudan">شحنة #SD-9021 وصلت بورتسودان</h4><p class="lang-text text-xs text-on-surface-variant mt-1" data-ar="منذ 15 دقيقة" data-en="15 minutes ago">منذ 15 دقيقة</p></div><span class="notif-dot w-2.5 h-2.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0"></span></div>
<div class="bg-surface-container-lowest p-5 rounded-xl border border-outline-variant industrial-shadow flex items-start gap-4"><div class="p-2 bg-red-100 rounded-lg text-red-600"><span class="material-symbols-outlined">warning</span></div><div class="flex-grow"><h4 class="lang-text font-bold text-primary text-sm" data-ar="مستودع الخرطوم: سعة حرجة 92%" data-en="Khartoum Warehouse: Critical 92%">مستودع الخرطوم: سعة حرجة 92%</h4><p class="lang-text text-xs text-on-surface-variant mt-1" data-ar="منذ ساعة" data-en="1 hour ago">منذ ساعة</p></div><span class="notif-dot w-2.5 h-2.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0"></span></div>
<div class="bg-surface-container-lowest p-5 rounded-xl border border-outline-variant industrial-shadow flex items-start gap-4"><div class="p-2 bg-green-100 rounded-lg text-green-600"><span class="material-symbols-outlined">payments</span></div><div class="flex-grow"><h4 class="lang-text font-bold text-primary text-sm" data-ar="تم استلام دفعة $12,400 من شركة النيل" data-en="Payment $12,400 received from Nile Co.">تم استلام دفعة $12,400 من شركة النيل</h4><p class="lang-text text-xs text-on-surface-variant mt-1" data-ar="منذ 3 ساعات" data-en="3 hours ago">منذ 3 ساعات</p></div><span class="notif-dot w-2.5 h-2.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0"></span></div>
<div class="bg-surface-container-lowest p-5 rounded-xl border border-outline-variant industrial-shadow flex items-start gap-4"><div class="p-2 bg-amber-100 rounded-lg text-amber-600"><span class="material-symbols-outlined">build</span></div><div class="flex-grow"><h4 class="lang-text font-bold text-primary text-sm" data-ar="صيانة مركبة TRK-007 مجدولة غداً" data-en="Vehicle TRK-007 maintenance scheduled tomorrow">صيانة مركبة TRK-007 مجدولة غداً</h4><p class="lang-text text-xs text-on-surface-variant mt-1" data-ar="منذ 5 ساعات" data-en="5 hours ago">منذ 5 ساعات</p></div><span class="notif-dot w-2.5 h-2.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0"></span></div>
<div class="bg-surface-container-lowest p-5 rounded-xl border border-outline-variant industrial-shadow flex items-start gap-4"><div class="p-2 bg-secondary-fixed rounded-lg text-secondary"><span class="material-symbols-outlined">sync</span></div><div class="flex-grow"><h4 class="lang-text font-bold text-primary text-sm" data-ar="مزامنة Odoo ERP اكتملت بنجاح" data-en="Odoo ERP sync completed successfully">مزامنة Odoo ERP اكتملت بنجاح</h4><p class="lang-text text-xs text-on-surface-variant mt-1" data-ar="منذ 6 ساعات" data-en="6 hours ago">منذ 6 ساعات</p></div><span class="notif-dot w-2.5 h-2.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0"></span></div>
</div></div>

<div id="view-profile" class="view-section transition-all duration-300 hidden">
<div class="mb-10"><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="الملف الشخصي" data-en="User Profile">الملف الشخصي</h2></div>
<div class="grid grid-cols-1 md:grid-cols-12 gap-gutter">
<div class="md:col-span-4 bg-surface-container-lowest p-8 rounded-xl border border-outline-variant industrial-shadow text-center">
<div class="w-24 h-24 rounded-full border-4 border-secondary mx-auto mb-4 overflow-hidden"><img class="w-full h-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBC1dqINOSMk1gUNU0yIVNSrO_mu9Lk4VCAmLB4IG9Hz6HqNoM0afQ6IcIISyoOVK3IEwvDkgBVuT3-b-yFNWp8SISrV5xNDVcLhyYZwYr4bzsjNhn9NKHpKTzSLsnoBwKvh_KPd4lEDWGysJHDAxkWjFc8RFX2QosIDhhAM_kuyYqkPTCDdGDY-l0TGy-RfAhVrO89c6Xr1LySllkaIdytj1wYGE-huYdmaUKgdFcK9d6NGLFUl1AG29l7l5KY6qkZWsbvSWCkGqc"/></div>
<h3 class="lang-text font-bold text-lg text-primary" data-ar="المدير التنفيذي" data-en="Executive Director">المدير التنفيذي</h3>
<p class="text-on-surface-variant text-sm">admin@sudanil.com</p>
<span class="lang-text inline-block mt-3 px-3 py-1 bg-secondary-container text-on-secondary-container text-xs rounded-full font-bold" data-ar="حساب متكامل معتمد" data-en="Certified Integrated Account">حساب متكامل معتمد</span>
</div>
<div class="md:col-span-8 bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow">
<h4 class="lang-text font-headline-md text-primary mb-6" data-ar="تعديل البيانات الشخصية" data-en="Edit Personal Data">تعديل البيانات الشخصية</h4>
<form class="space-y-4" onsubmit="event.preventDefault();triggerToastAlert('تم الحفظ بنجاح','Saved successfully')">
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="الاسم الكامل" data-en="Full Name">الاسم الكامل</label><input class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" value="المدير التنفيذي"/></div>
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="البريد الإلكتروني" data-en="Email">البريد الإلكتروني</label><input class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" value="admin@sudanil.com"/></div>
</div>
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="الهاتف" data-en="Phone">الهاتف</label><input class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" value="+249 912 345 678"/></div>
<h4 class="lang-text font-bold text-primary pt-4 border-t border-outline-variant" data-ar="تغيير كلمة المرور" data-en="Change Password">تغيير كلمة المرور</h4>
<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="الحالية" data-en="Current">الحالية</label><input type="password" class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" placeholder="••••••"/></div>
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="الجديدة" data-en="New">الجديدة</label><input type="password" class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" placeholder="••••••"/></div>
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="تأكيد" data-en="Confirm">تأكيد</label><input type="password" class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" placeholder="••••••"/></div>
</div>
<div class="flex justify-end pt-4"><button type="submit" class="lang-text px-6 py-2.5 bg-primary-container text-white rounded-lg font-bold hover:bg-black transition-colors" data-ar="حفظ التغييرات" data-en="Save Changes">حفظ التغييرات</button></div>
</form></div></div></div>

<div id="view-support" class="view-section transition-all duration-300 hidden">
<div class="mb-10"><h2 class="lang-text font-headline-lg text-headline-lg text-primary" data-ar="الدعم الفني" data-en="Technical Support">الدعم الفني</h2></div>
<div class="grid grid-cols-1 md:grid-cols-12 gap-gutter">
<div class="md:col-span-8 bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow">
<h4 class="lang-text font-headline-md text-primary mb-6" data-ar="إنشاء تذكرة دعم" data-en="Create Support Ticket">إنشاء تذكرة دعم</h4>
<form class="space-y-4" onsubmit="event.preventDefault();triggerToastAlert('تم إرسال التذكرة بنجاح','Ticket submitted successfully')">
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="العنوان" data-en="Subject">العنوان</label><input class="lang-text w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none" placeholder="وصف المشكلة..." data-ar="وصف المشكلة..." data-en="Describe the issue..."/></div>
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="التفاصيل" data-en="Details">التفاصيل</label><textarea class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none h-28 resize-none" placeholder="..."></textarea></div>
<div class="grid grid-cols-2 gap-4">
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="الأولوية" data-en="Priority">الأولوية</label><select class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none"><option class="lang-text" data-ar="عادي" data-en="Normal">عادي</option><option class="lang-text" data-ar="متوسط" data-en="Medium">متوسط</option><option class="lang-text" data-ar="عاجل" data-en="Urgent">عاجل</option></select></div>
<div><label class="lang-text block text-xs font-bold text-on-surface-variant mb-2" data-ar="النوع" data-en="Type">النوع</label><select class="w-full px-4 py-2.5 bg-surface-container border border-outline-variant rounded-lg text-sm text-primary focus:ring-2 focus:ring-secondary focus:outline-none"><option class="lang-text" data-ar="تقني" data-en="Technical">تقني</option><option class="lang-text" data-ar="مالي" data-en="Financial">مالي</option><option class="lang-text" data-ar="شحن" data-en="Shipping">شحن</option></select></div>
</div>
<div class="flex justify-end"><button type="submit" class="lang-text px-6 py-2.5 bg-secondary-container text-on-secondary-container rounded-lg font-bold hover:bg-secondary-fixed transition-colors" data-ar="إرسال التذكرة" data-en="Submit Ticket">إرسال التذكرة</button></div>
</form></div>
<div class="md:col-span-4 bg-surface-container-lowest p-6 rounded-xl border border-outline-variant industrial-shadow">
<h4 class="lang-text font-headline-md text-primary mb-6" data-ar="معلومات الاتصال" data-en="Contact Info">معلومات الاتصال</h4>
<div class="space-y-4">
<div class="flex items-center gap-3"><span class="material-symbols-outlined text-secondary">mail</span><div><p class="text-xs text-on-surface-variant font-bold">Email</p><p class="text-sm text-primary font-medium">support@sudanil.com</p></div></div>
<div class="flex items-center gap-3"><span class="material-symbols-outlined text-secondary">call</span><div><p class="text-xs text-on-surface-variant font-bold">Phone</p><p class="text-sm text-primary font-medium">+249 183 123 456</p></div></div>
<div class="flex items-center gap-3"><span class="material-symbols-outlined text-secondary">schedule</span><div><p class="lang-text text-xs text-on-surface-variant font-bold" data-ar="ساعات العمل" data-en="Working Hours">ساعات العمل</p><p class="lang-text text-sm text-primary font-medium" data-ar="الأحد - الخميس: 8ص - 5م" data-en="Sun - Thu: 8AM - 5PM">الأحد - الخميس: 8ص - 5م</p></div></div>
</div></div></div></div>
`;
hr.insertAdjacentHTML('afterend',h);
}
document.addEventListener('DOMContentLoaded',injectSystemSections);
